// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujzkgezxodsxlsawptby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqemtnZXp4b2RzeGxzYXdwdGJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNzQ4OTUsImV4cCI6MjA2MDk1MDg5NX0.8LAR1nng-Ff9sj38Rjrbj5uRiImbLbr7q8gktPAPOdA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);